"""
Phase 7: Program Management Positioning = deterministic ownership-verb scan
(app/aerospace_engine/ownership_scan.py, always runs, no API key needed) +
optional LLM bullet-quality depth (spec Layer 8: Action+Scope+Technical
Context+Result scoring per bullet).

run_pm_positioning() is the single entry point app/main.py calls -- it
degrades gracefully to deterministic-only when the LLM isn't configured or
errors, rather than raising past this module.
"""
from __future__ import annotations

from app.aerospace_engine.ownership_scan import scan_ownership_language
from app.config import LLM_MODEL
from app.llm.client import LLMCallError, LLMNotConfiguredError, call_tool
from app.llm.schemas import BULLET_QUALITY_SCHEMA
from app.models import (
    Finding,
    FindingCategory,
    PriorityBucket,
    RiskClassification,
    Severity,
    SourceCitation,
    SourceConfidence,
    TargetProfile,
)

_SYSTEM_PROMPT = """You are an institutional-quality aerospace/defense program-management resume reviewer, \
scoring individual experience bullets for Action + Scope + Technical Context + Result quality.

Hard rules:
- Never fabricate a metric, dollar value, team size, or outcome that isn't stated in the bullet.
- When a bullet would clearly benefit from one missing concrete fact, name exactly ONE such variable rather \
than a vague "add more detail."
- A rewrite_suggestion must use only facts already present in the original bullet -- if you cannot improve it \
without inventing something, return null instead of guessing.
- Prioritize the candidate's most senior/most recent roles when choosing which bullets to score.
"""

_MAX_FINDINGS_FROM_WEAK_BULLETS = 5
_MAX_FINDINGS_FROM_LLM_BULLETS = 5
_LOW_BULLET_SCORE_THRESHOLD = 5.0  # out of 10, averaged across the 6 dimensions


def _ownership_source() -> list[SourceCitation]:
    return [
        SourceCitation(
            source="Internal ownership-verb database heuristic (Level E, not yet backed by a fetched citation)",
            confidence=SourceConfidence.E,
            claim="Bullets opening with weak-participation language (helped/supported/assisted/...) vs. ownership language (led/directed/delivered/...).",
            supports_rule="ownership_language_scan",
        )
    ]


def _llm_source() -> list[SourceCitation]:
    return [
        SourceCitation(
            source=f"LLM judgment (model: {LLM_MODEL})",
            confidence=SourceConfidence.E,
            claim="Per-bullet Action+Scope+Technical Context+Result scoring generated by the configured Anthropic model.",
            supports_rule="llm_bullet_quality",
        )
    ]


def run_pm_positioning(full_text: str, target: TargetProfile, next_id) -> tuple[dict, list[Finding]]:
    findings: list[Finding] = []

    scan = scan_ownership_language(full_text)
    for hit in scan.weak_hits[:_MAX_FINDINGS_FROM_WEAK_BULLETS]:
        findings.append(
            Finding(
                id=next_id(),
                category=FindingCategory.PROGRAM_MANAGEMENT,
                classification=RiskClassification.HUMAN_RECRUITER_RISK,
                severity=Severity.YELLOW,
                title="Bullet opens with weak-participation language",
                description=f"Bullet begins with '{hit.verb}': \"{hit.line[:160]}\"",
                why_it_matters="Program-management resumes should show ownership of outcomes, not just participation. Weak opening verbs undersell demonstrated scope.",
                ats_evidence=f"Line starts with weak-participation verb '{hit.verb}'.",
                recruiter_impact="Reads as a supporting contributor rather than the person who drove the outcome, even if the underlying work was substantial.",
                recommended_change="Open with an ownership verb (led, directed, delivered, owned, drove, ...) if the candidate genuinely drove this outcome.",
                confidence=SourceConfidence.E,
                sources=_ownership_source(),
                priority=PriorityBucket.OPTIONAL_POLISH,
            )
        )

    result = {
        "ownership_count": len(scan.ownership_hits),
        "weak_count": len(scan.weak_hits),
        "ownership_ratio": scan.ownership_ratio,
        "llm_ran": False,
        "bullets": [],
        "ownership_language_note": None,
    }

    try:
        user_content = (
            f"Target profile: {target.career_path or 'unspecified'} / {target.seniority or 'unspecified seniority'}\n\n"
            f"Resume text:\n{full_text[:12000]}"
        )
        llm_result = call_tool(
            system=_SYSTEM_PROMPT,
            user_content=user_content,
            tool_name=BULLET_QUALITY_SCHEMA["name"],
            tool_description=BULLET_QUALITY_SCHEMA["description"],
            input_schema=BULLET_QUALITY_SCHEMA["input_schema"],
            max_tokens=2500,
        )
        result["llm_ran"] = True
        result["bullets"] = llm_result.get("bullets", [])
        result["ownership_language_note"] = llm_result.get("ownership_language_note")

        for bullet in result["bullets"][:_MAX_FINDINGS_FROM_LLM_BULLETS]:
            dims = [
                bullet.get("ownership_score", 0), bullet.get("specificity_score", 0),
                bullet.get("scope_score", 0), bullet.get("technical_context_score", 0),
                bullet.get("metric_strength_score", 0), bullet.get("outcome_score", 0),
            ]
            avg = sum(dims) / len(dims) if dims else 0
            if avg >= _LOW_BULLET_SCORE_THRESHOLD:
                continue
            rewrite = bullet.get("rewrite_suggestion")
            missing = bullet.get("missing_variable")
            recommended = rewrite or (f"Add the missing {missing}." if missing else "Strengthen this bullet's weakest dimension.")
            findings.append(
                Finding(
                    id=next_id(),
                    category=FindingCategory.ACCOMPLISHMENT_STRENGTH,
                    classification=RiskClassification.POSITIONING_OPPORTUNITY,
                    severity=Severity.YELLOW if avg >= 3 else Severity.ORANGE,
                    title=f"Bullet weak on {bullet.get('weakest_dimension', 'overall strength')}",
                    description=f"\"{bullet.get('bullet_text', '')[:180]}\"",
                    why_it_matters="Strong bullets combine Action + Scope + Technical Context + Result; a weak dimension makes the accomplishment harder to evaluate.",
                    ats_evidence=f"LLM-scored average {avg:.1f}/10 across ownership/specificity/scope/technical-context/metric/outcome dimensions.",
                    recommended_change=recommended,
                    suggested_rewrite=[rewrite] if rewrite else None,
                    confidence=SourceConfidence.E,
                    sources=_llm_source(),
                    priority=PriorityBucket.STRONGLY_RECOMMENDED if avg < 3 else PriorityBucket.OPTIONAL_POLISH,
                )
            )
    except (LLMNotConfiguredError, LLMCallError):
        pass  # deterministic ownership-scan result above still stands on its own

    return result, findings
