"""
Phase 6 (LLM-powered): career narrative, seniority calibration,
professional-summary evaluation, recruiter readability, and years-of-
experience positioning (spec Layers 5, 10, 11, 12).

Raises LLMNotConfiguredError / LLMCallError (from app.llm.client) on
failure -- callers (app/main.py) are responsible for catching those and
degrading the affected scores, never the whole /api/analyze request.
"""
from __future__ import annotations

from app.llm.client import call_tool
from app.llm.schemas import POSITIONING_ANALYSIS_SCHEMA
from app.models import (
    Finding,
    FindingCategory,
    PriorityBucket,
    RiskClassification,
    Severity,
    SourceCitation,
    SourceConfidence,
    TargetProfile,
)
from app.config import LLM_MODEL

_SYSTEM_PROMPT = """You are an institutional-quality resume career-positioning analyst, specializing in \
aerospace, defense, space, and advanced-manufacturing program management. You evaluate a resume's narrative \
clarity, seniority calibration, and recruiter readability against a candidate's stated target role.

Hard rules:
- Never fabricate facts, metrics, employers, or dates not present in the resume text.
- Never reflexively recommend adding a professional summary -- judge whether this specific candidate's career \
history benefits from one (e.g. someone moving between disciplines) versus an obviously linear trajectory that \
doesn't need one.
- Flag generic corporate filler ("results-driven professional", "proven track record", "strategic thinker") \
without substantive evidence behind it -- don't let it pass as a positioning strength.
- Seniority calibration must be checked in both directions: flag wording that undersells demonstrated scope AND \
wording that overstates scope beyond what's actually shown.
- Be specific and evidence-based in every rationale -- reference what the resume actually says, not generic advice.
"""


def _target_profile_text(target: TargetProfile) -> str:
    lines = []
    if target.industry:
        lines.append(f"Industry: {target.industry}")
    if target.career_path:
        lines.append(f"Career Path: {target.career_path}")
    if target.target_role:
        lines.append(f"Target Role: {target.target_role}")
    if target.seniority:
        lines.append(f"Target Seniority: {target.seniority}")
    if target.target_company:
        lines.append(f"Target Company: {target.target_company}")
    if target.background_notes:
        lines.append(f"Background Notes: {target.background_notes}")
    return "\n".join(lines) if lines else "(No target role information supplied.)"


def evaluate_positioning(full_text: str, target: TargetProfile, next_id) -> tuple[dict, list[Finding]]:
    user_content = (
        f"Target profile:\n{_target_profile_text(target)}\n\n"
        f"Resume text (extracted, reading order may not be perfectly preserved):\n{full_text[:12000]}"
    )

    result = call_tool(
        system=_SYSTEM_PROMPT,
        user_content=user_content,
        tool_name=POSITIONING_ANALYSIS_SCHEMA["name"],
        tool_description=POSITIONING_ANALYSIS_SCHEMA["description"],
        input_schema=POSITIONING_ANALYSIS_SCHEMA["input_schema"],
        max_tokens=2000,
    )

    source = [
        SourceCitation(
            source=f"LLM judgment (model: {LLM_MODEL})",
            confidence=SourceConfidence.E,
            claim="Career-positioning analysis generated by the configured Anthropic model, not a deterministic rule.",
            supports_rule="llm_positioning_analysis",
        )
    ]

    findings: list[Finding] = []
    for flag in result.get("flags", []):
        severity_str = flag.get("severity", "yellow")
        severity = Severity.ORANGE if severity_str == "orange" else Severity.YELLOW
        findings.append(
            Finding(
                id=next_id(),
                category=FindingCategory.CAREER_POSITIONING,
                classification=RiskClassification.POSITIONING_OPPORTUNITY,
                severity=severity,
                title=flag.get("title", "Career positioning issue"),
                description=flag.get("why_it_matters", ""),
                why_it_matters=flag.get("why_it_matters", ""),
                ats_evidence="Not an ATS/parsing finding -- a recruiter-perception judgment from LLM analysis of the resume narrative.",
                recruiter_impact=flag.get("why_it_matters", ""),
                recommended_change=flag.get("recommended_change", ""),
                confidence=SourceConfidence.E,
                sources=source,
                priority=PriorityBucket.STRONGLY_RECOMMENDED if severity == Severity.ORANGE else PriorityBucket.OPTIONAL_POLISH,
            )
        )

    return result, findings
